# Generated by Django 5.2

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def assign_owners(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    Category = apps.get_model("inventory", "Category")
    Product = apps.get_model("inventory", "Product")
    user = User.objects.order_by("id").first()
    if user is None:
        Product.objects.all().delete()
        Category.objects.all().delete()
        return
    Category.objects.filter(owner__isnull=True).update(owner=user)
    Product.objects.filter(owner__isnull=True).update(owner=user)


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="is_archived",
            field=models.BooleanField(
                default=False,
                help_text="Removed from the picker; kept so existing products still have a category.",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="owner",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="categories",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="owner",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RunPython(assign_owners, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="category",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="categories",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="product",
            name="barcode",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddConstraint(
            model_name="category",
            constraint=models.UniqueConstraint(
                fields=("owner", "name"), name="uniq_category_per_owner"
            ),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.UniqueConstraint(
                condition=models.Q(("barcode__isnull", False))
                & ~models.Q(("barcode", "")),
                fields=("owner", "barcode"),
                name="uniq_barcode_per_owner",
            ),
        ),
    ]
