# Generated by Django 5.2.17 on 2026-09-11 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_per_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='bio',
            field=models.TextField(blank=True, default='', help_text='Product description/bio'),
        ),
    ]
