# Generated by Django 5.2.17 on 2026-08-31 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_paymentproof'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_price', models.DecimalField(decimal_places=2, default=70.0, help_text='Monthly premium price in PHP', max_digits=8)),
                ('gcash_number', models.CharField(default='0917 000 0070', help_text='GCash receiver mobile number', max_length=50)),
                ('gcash_name', models.CharField(default='STORA Admin', help_text='GCash receiver account name', max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Subscription Pricing & Settings',
                'verbose_name_plural': 'Subscription Pricing & Settings',
            },
        ),
    ]
