# Generated by Django 5.2.17 on 2026-09-10 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_aiinsight_storelocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionconfig',
            name='qr_code',
            field=models.ImageField(blank=True, help_text='Upload custom GCash / InstaPay QR code image', null=True, upload_to='subscription_qr/'),
        ),
    ]
