# Generated by Django 5.2.17 on 2026-09-10 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_subscriptionconfig_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('owner', 'Store Owner'), ('customer', 'Customer')], default='owner', max_length=20),
        ),
    ]
