# Generated by Django 5.2.17 on 2026-09-11 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='block_reason',
            field=models.CharField(blank=True, default='', help_text='Reason why the user was blocked.', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='is_blocked',
            field=models.BooleanField(default=False, help_text='Designates whether this user (customer or owner) is blocked from using the app.'),
        ),
    ]
