# Generated by Django 5.2.17 on 2026-09-14 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_user_block_reason_user_is_blocked'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aiinsight',
            options={'ordering': ['-created_at'], 'verbose_name': 'Business Insight', 'verbose_name_plural': 'Business Insights'},
        ),
    ]
