# Generated by Django 5.2.17 on 2026-09-15 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_aiinsight_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='storelocation',
            name='is_open',
            field=models.BooleanField(default=True),
        ),
    ]
