# Generated by Django 5.2.17 on 2026-09-30 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_enable_rls_all_tables'),
    ]

    operations = [
        migrations.AddField(
            model_name='storelocation',
            name='payment_account_name',
            field=models.CharField(blank=True, default='', help_text="Store's payment receiver name", max_length=150),
        ),
        migrations.AddField(
            model_name='storelocation',
            name='payment_phone_number',
            field=models.CharField(blank=True, default='', help_text="Store's GCash / mobile payment number", max_length=50),
        ),
        migrations.AddField(
            model_name='storelocation',
            name='payment_qr_code',
            field=models.ImageField(blank=True, help_text='Custom payment QR code image', null=True, upload_to='store_qr/'),
        ),
    ]
