# Generated by Django 5.2.17 on 2026-09-30 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_storelocation_payment_account_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorePaymentMethod',
            fields=[
            ],
            options={
                'verbose_name': 'Store QR Code & Number',
                'verbose_name_plural': 'Store QR Codes & Numbers',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.storelocation',),
        ),
    ]
