# Generated by Django 5.2.17 on 2026-09-30 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_storepaymentmethod'),
    ]

    operations = [
        migrations.AddField(
            model_name='storelocation',
            name='accept_gcash_payments',
            field=models.BooleanField(default=True, help_text='Allow customers to pay via GCash / mobile payment at checkout'),
        ),
    ]
