# Generated by Django 5.2.17 on 2026-10-05 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_storelocation_accept_gcash_payments'),
    ]

    operations = [
        migrations.AddField(
            model_name='storelocation',
            name='payment_accounts',
            field=models.JSONField(blank=True, default=list, help_text='List of configured payment accounts'),
        ),
        migrations.AddField(
            model_name='storelocation',
            name='show_single_account',
            field=models.BooleanField(default=False, help_text='Display only primary/single payment account to customers'),
        ),
    ]
