# Generated by Django 5.2.17 on 2026-09-05 03:52

import orders.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='expires_at',
            field=models.DateTimeField(default=orders.models.default_order_expiry),
        ),
    ]
