# Generated by Django 5.2.17 on 2026-09-05 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('ready', 'Ready for Pickup'), ('declined', 'Declined'), ('auto_declined', 'Auto‑Declined'), ('counter_offer', 'Counter‑Offer')], default='pending', max_length=20),
        ),
    ]
