# Generated by Django 5.2.17 on 2026-09-30 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_add_status_completed_to_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash on Pickup'), ('gcash', 'GCash / Online Payment')], default='cash', max_length=20),
        ),
    ]
