# Generated by Django 5.2.17 on 2026-09-11 14:54

import api.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        ('orders', '0003_alter_order_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('harassment', 'Harassment / Abusive Behavior'), ('fraud', 'Fraud / Scam / Non-payment'), ('inappropriate_content', 'Inappropriate Content / Photos'), ('spam', 'Spam / Unsolicited Messages'), ('fake_order', 'Fake Order / Bogus Customer / Bogus Store'), ('other', 'Other Violation')], default='other', max_length=50)),
                ('description', models.TextField(blank=True, default='')),
                ('attachment', models.ImageField(blank=True, null=True, upload_to=api.models.report_attachment_upload_path)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('reviewed', 'Under Review'), ('action_taken', 'Action Taken (User Blocked)'), ('dismissed', 'Dismissed')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='orders.order')),
                ('reported_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_reports', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filed_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='api_userrep_status_52907b_idx'), models.Index(fields=['reported_user', 'status'], name='api_userrep_reporte_2a07c9_idx')],
            },
        ),
    ]
