# Generated by Django 5.2.17 on 2026-09-12 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_userreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='is_unsent',
            field=models.BooleanField(default=False),
        ),
    ]
