# Generated by Django 5.2.17 on 2026-09-12 15:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_chatmessage_is_unsent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='deleted_by_users',
            field=models.ManyToManyField(blank=True, related_name='deleted_chat_messages', to=settings.AUTH_USER_MODEL),
        ),
    ]
