# Generated by Django 5.2.17 on 2026-09-15 15:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_chatmessage_deleted_by_users'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blockedcustomer',
            options={'ordering': ['-created_at'], 'verbose_name': 'Blocked User', 'verbose_name_plural': 'Blocked Users'},
        ),
        migrations.AlterField(
            model_name='blockedcustomer',
            name='customer',
            field=models.ForeignKey(blank=True, help_text='Customer (leave empty if blocking a store owner globally / by admin)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blocked_by_owners', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='blockedcustomer',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Store Owner (leave empty if blocking a customer globally / by admin)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blocked_customers', to=settings.AUTH_USER_MODEL),
        ),
    ]
