# Generated by Django 5.2.17 on 2026-09-16 01:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_blockedcustomer_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blockedcustomer',
            options={'ordering': ['-created_at'], 'verbose_name': 'Blocked Customer/Owner', 'verbose_name_plural': 'Blocked Customers/Owners'},
        ),
        migrations.AddField(
            model_name='blockedcustomer',
            name='block_side',
            field=models.CharField(choices=[('both', 'Both Sides (Full Chat Block - Neither can message)'), ('customer', 'Customer Side Only (Customer cannot send messages)'), ('owner', 'Owner Side Only (Owner cannot send messages)')], default='both', help_text='Choose which side is blocked from sending messages.', max_length=20),
        ),
        migrations.AddField(
            model_name='blockedcustomer',
            name='reason',
            field=models.CharField(blank=True, default='', help_text='Optional reason or note for this message block.', max_length=255),
        ),
        migrations.AlterField(
            model_name='blockedcustomer',
            name='customer',
            field=models.ForeignKey(blank=True, help_text='Customer (leave empty if blocking a store owner globally from messaging)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blocked_by_owners', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='blockedcustomer',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Store Owner (leave empty if blocking a customer globally across all stores)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blocked_customers', to=settings.AUTH_USER_MODEL),
        ),
    ]
