# Generated by Django 5.2.17 on 2026-09-16 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_blockedcustomer_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blockedcustomer',
            name='reason',
        ),
    ]
