# Generated by Django 5.2

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def assign_sale_owners(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    Sale = apps.get_model("sales", "Sale")
    SaleItem = apps.get_model("sales", "SaleItem")
    user = User.objects.order_by("id").first()
    if user is None:
        Sale.objects.all().delete()
        return
    Sale.objects.filter(owner__isnull=True).update(owner=user)
    for item in SaleItem.objects.select_related("product"):
        if not item.product_name:
            item.product_name = item.product.name
            item.save(update_fields=["product_name"])


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("sales", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sale",
            name="owner",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sales",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="saleitem",
            name="product_name",
            field=models.CharField(default="", max_length=150),
            preserve_default=False,
        ),
        migrations.RunPython(assign_sale_owners, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="sale",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sales",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
