# Generated by Django 5.2.17 on 2026-09-17 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_status'),
        ('sales', '0003_saleitem_product_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='channel',
            field=models.CharField(default='in_store', max_length=20),
        ),
        migrations.AddField(
            model_name='sale',
            name='customer_name',
            field=models.CharField(blank=True, default='Walk-in Customer', max_length=150),
        ),
        migrations.AddField(
            model_name='sale',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='orders.order'),
        ),
        migrations.AddField(
            model_name='sale',
            name='receipt_number',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
