# Generated by Django 5.2.17 on 2026-09-28 12:46

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_change_product_category_to_protect'),
        ('sales', '0005_backfill_online_order_channel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=150)),
                ('customer_phone', models.CharField(blank=True, default='', max_length=32)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('settled', 'Settled'), ('overdue', 'Overdue')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_credits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Customer Loan / Utang',
                'verbose_name_plural': 'Customer Loans / Utang',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CreditPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(default='cash', max_length=32)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('paid_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('credit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='sales.customercredit')),
            ],
            options={
                'ordering': ['-paid_at'],
            },
        ),
        migrations.CreateModel(
            name='CreditItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=150)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_items', to='inventory.product')),
                ('credit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.customercredit')),
            ],
        ),
    ]
